/*
 * This source file was generated by the Gradle 'init' task
 */
package org.csc335;

import java.io.IOException;

import org.csc335.controllers.Game;
import org.csc335.navigation.Navigation;

import javafx.application.Application;
import javafx.scene.text.Font;
import javafx.stage.Stage;

public class App extends Application {
  @Override
  public void start(Stage stage) throws IOException {
    Font.loadFont(this.getClass().getResource("/fonts/fa-solid-900.ttf").toExternalForm(), 12);

    stage.setTitle("2048 FX");
    stage.setWidth(900);
    stage.setHeight(800);

    Navigation.setStage(stage);

    Navigation.navigate(new Game());
  }

  public static void main(String[] args) {
    launch(args);
  }

}
